# Please edit this configuration file to match your environment (on Windows).
# Examples in comments below - check/change the paths.
#
#

execution_engine: asyncio
logger:
  type: file
  level: error
  truncate_tools: true

# Default model configuration
model:
  provider: openai
  name: gpt-4o

mcp:
  servers:
    filesystem:
      command: "npx"
      args: ["@modelcontextprotocol/server-filesystem"]
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    fatzebra:
      command: "node"
      args: ["../mcp-fat-zebra/dist/index.js"]
    brave_search_api:
      command: "npx"
      args: ["@modelcontextprotocol/server-brave-search"]
